# Generated by Django 3.0.2 on 2020-01-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(max_length=25)),
                ('origen', models.CharField(max_length=7)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=3)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('modalidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=1)),
                ('plazo', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=8)),
                ('hora', models.TimeField()),
                ('duracion', models.FloatField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Aula')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Periodo'),
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.CharField(max_length=10)),
                ('valor', models.CharField(max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingles.Grupo')),
            ],
        ),
    ]
